/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'dry_fish' : null } |
  { 'chutney' : null } |
  { 'fresh_fish' : null } |
  { 'masala' : null };
export interface CreateOrderInput {
  'customer' : CustomerDetails,
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
}
export interface CustomerDetails {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'customer' : CustomerDetails,
  'createdAt' : Timestamp,
  'totalAmount' : bigint,
  'stripePaymentIntentId' : [] | [string],
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'weight' : [] | [string],
  'productId' : ProductId,
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null };
export interface Product {
  'id' : ProductId,
  'stockQuantity' : bigint,
  'featured' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'category' : Category,
  'basePrice' : bigint,
  'weightOptions' : Array<WeightOption>,
  'images' : Array<ExternalBlob>,
}
export type ProductId = bigint;
export interface ProductInput {
  'stockQuantity' : bigint,
  'featured' : boolean,
  'name' : string,
  'description' : string,
  'category' : Category,
  'basePrice' : bigint,
  'weightOptions' : Array<WeightOption>,
}
export interface Review {
  'id' : ReviewId,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'reviewerName' : string,
  'comment' : string,
  'rating' : bigint,
}
export type ReviewId = bigint;
export interface ReviewInput {
  'productId' : ProductId,
  'reviewerName' : string,
  'comment' : string,
  'rating' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface WeightOption { 'weight' : string, 'price' : bigint }
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<[string, ProductInput], Product>,
  'addProductImage' : ActorMethod<[string, ProductId, ExternalBlob], boolean>,
  'addReview' : ActorMethod<[ReviewInput], Review>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[CreateOrderInput], Order>,
  'deleteProduct' : ActorMethod<[string, ProductId], boolean>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductReviews' : ActorMethod<[ProductId], Array<Review>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'listOrders' : ActorMethod<[string], Array<Order>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'setAdminKey' : ActorMethod<[string, string], boolean>,
  'setOrderPaymentIntent' : ActorMethod<
    [string, OrderId, string],
    [] | [Order]
  >,
  'setStripeConfiguration' : ActorMethod<
    [string, StripeConfiguration],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<
    [string, OrderId, OrderStatus],
    [] | [Order]
  >,
  'updateProduct' : ActorMethod<
    [string, ProductId, ProductInput],
    [] | [Product]
  >,
  'updateStock' : ActorMethod<[string, ProductId, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];