/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Variant({
  'dry_fish' : IDL.Null,
  'chutney' : IDL.Null,
  'fresh_fish' : IDL.Null,
  'masala' : IDL.Null,
});
export const WeightOption = IDL.Record({
  'weight' : IDL.Text,
  'price' : IDL.Nat,
});
export const ProductInput = IDL.Record({
  'stockQuantity' : IDL.Nat,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'basePrice' : IDL.Nat,
  'weightOptions' : IDL.Vec(WeightOption),
});
export const ProductId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : ProductId,
  'stockQuantity' : IDL.Nat,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'category' : Category,
  'basePrice' : IDL.Nat,
  'weightOptions' : IDL.Vec(WeightOption),
  'images' : IDL.Vec(ExternalBlob),
});
export const ReviewInput = IDL.Record({
  'productId' : ProductId,
  'reviewerName' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ReviewId = IDL.Nat;
export const Review = IDL.Record({
  'id' : ReviewId,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'reviewerName' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const CustomerDetails = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'weight' : IDL.Opt(IDL.Text),
  'productId' : ProductId,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const CreateOrderInput = IDL.Record({
  'customer' : CustomerDetails,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'customer' : CustomerDetails,
  'createdAt' : Timestamp,
  'totalAmount' : IDL.Nat,
  'stripePaymentIntentId' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(OrderItem),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addProduct' : IDL.Func([IDL.Text, ProductInput], [Product], []),
  'addProductImage' : IDL.Func(
      [IDL.Text, ProductId, ExternalBlob],
      [IDL.Bool],
      [],
    ),
  'addReview' : IDL.Func([ReviewInput], [Review], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func([CreateOrderInput], [Order], []),
  'deleteProduct' : IDL.Func([IDL.Text, ProductId], [IDL.Bool], []),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProductsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'setAdminKey' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'setOrderPaymentIntent' : IDL.Func(
      [IDL.Text, OrderId, IDL.Text],
      [IDL.Opt(Order)],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([IDL.Text, StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateOrderStatus' : IDL.Func(
      [IDL.Text, OrderId, OrderStatus],
      [IDL.Opt(Order)],
      [],
    ),
  'updateProduct' : IDL.Func(
      [IDL.Text, ProductId, ProductInput],
      [IDL.Opt(Product)],
      [],
    ),
  'updateStock' : IDL.Func([IDL.Text, ProductId, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Variant({
    'dry_fish' : IDL.Null,
    'chutney' : IDL.Null,
    'fresh_fish' : IDL.Null,
    'masala' : IDL.Null,
  });
  const WeightOption = IDL.Record({ 'weight' : IDL.Text, 'price' : IDL.Nat });
  const ProductInput = IDL.Record({
    'stockQuantity' : IDL.Nat,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'basePrice' : IDL.Nat,
    'weightOptions' : IDL.Vec(WeightOption),
  });
  const ProductId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : ProductId,
    'stockQuantity' : IDL.Nat,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'category' : Category,
    'basePrice' : IDL.Nat,
    'weightOptions' : IDL.Vec(WeightOption),
    'images' : IDL.Vec(ExternalBlob),
  });
  const ReviewInput = IDL.Record({
    'productId' : ProductId,
    'reviewerName' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ReviewId = IDL.Nat;
  const Review = IDL.Record({
    'id' : ReviewId,
    'createdAt' : Timestamp,
    'productId' : ProductId,
    'reviewerName' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const CustomerDetails = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'weight' : IDL.Opt(IDL.Text),
    'productId' : ProductId,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const CreateOrderInput = IDL.Record({
    'customer' : CustomerDetails,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'customer' : CustomerDetails,
    'createdAt' : Timestamp,
    'totalAmount' : IDL.Nat,
    'stripePaymentIntentId' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(OrderItem),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addProduct' : IDL.Func([IDL.Text, ProductInput], [Product], []),
    'addProductImage' : IDL.Func(
        [IDL.Text, ProductId, ExternalBlob],
        [IDL.Bool],
        [],
      ),
    'addReview' : IDL.Func([ReviewInput], [Review], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func([CreateOrderInput], [Order], []),
    'deleteProduct' : IDL.Func([IDL.Text, ProductId], [IDL.Bool], []),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductReviews' : IDL.Func([ProductId], [IDL.Vec(Review)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listOrders' : IDL.Func([IDL.Text], [IDL.Vec(Order)], []),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'setAdminKey' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'setOrderPaymentIntent' : IDL.Func(
        [IDL.Text, OrderId, IDL.Text],
        [IDL.Opt(Order)],
        [],
      ),
    'setStripeConfiguration' : IDL.Func(
        [IDL.Text, StripeConfiguration],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateOrderStatus' : IDL.Func(
        [IDL.Text, OrderId, OrderStatus],
        [IDL.Opt(Order)],
        [],
      ),
    'updateProduct' : IDL.Func(
        [IDL.Text, ProductId, ProductInput],
        [IDL.Opt(Product)],
        [],
      ),
    'updateStock' : IDL.Func([IDL.Text, ProductId, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };